# Generated by Django 4.1 on 2022-09-28 17:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rink',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rink_type', models.CharField(max_length=64, null=True)),
                ('rink_source', models.CharField(max_length=64, null=True)),
                ('comment', models.TextField(blank=True, null='True')),
            ],
            options={
                'db_table': 'personal_module_portal_rink',
            },
        ),
    ]
