# Generated by Django 4.1 on 2022-09-25 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rink',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rink_recipient', to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
        migrations.AddField(
            model_name='rink',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rink_sender', to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
    ]
