# Generated by Django 4.1 on 2022-09-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rink',
            table='personal_module_portal_rink',
        ),
    ]
