# Generated by Django 4.1 on 2022-10-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_module_teachers', '0001_initial'),
        ('school_module_classes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='class_abbreviation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_teachers.teacher', to_field='id'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_classes.department', to_field='id'),
        ),
    ]
