# Generated by Django 4.1 on 2022-10-21 11:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school_module_teachers', '0001_initial'),
        ('school_module_classes', '0003_clase_class_abbreviation_alter_clase_class_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_teachers.teacher', to_field='id'),
        ),
        migrations.CreateModel(
            name='DepartmentClass',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_classes.clase', to_field='id')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_classes.department', to_field='id')),
            ],
            options={
                'db_table': 'school_module_department_class',
            },
        ),
    ]
