# Generated by Django 4.1 on 2023-02-13 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_module_patients', '0001_initial'),
        ('hospital_module_laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital_module_patients.patient', to_field='id'),
        ),
    ]
