# Generated by Django 4.1 on 2022-11-28 07:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association_module_members', '0001_initial'),
        ('association_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('committee_name', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_commissioned', models.DateField(blank=True, null=True)),
                ('date_decommissioned', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='association_account.account', to_field='id')),
                ('committee_chairman', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='association_module_members.member', to_field='id')),
            ],
            options={
                'db_table': 'association_module_committee',
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='association_module_committees.committee', to_field='id')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='association_module_members.member', to_field='id')),
            ],
            options={
                'db_table': 'association_module_committee_member',
            },
        ),
    ]
