# Generated by Django 4.1 on 2022-12-29 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association_module_members', '0001_initial'),
        ('association_module_committees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='committee_chairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='association_module_members.member', to_field='id'),
        ),
    ]
