# Generated by Django 4.1 on 2022-09-27 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roster', '0001_initial'),
        ('accounts', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpersonnel',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='staff.staff', to_field='id'),
        ),
        migrations.AddField(
            model_name='shift',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roster.roster', to_field='id'),
        ),
        migrations.AddField(
            model_name='rosterday',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roster.batch', to_field='id'),
        ),
        migrations.AddField(
            model_name='rosterday',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roster.roster', to_field='id'),
        ),
        migrations.AddField(
            model_name='rosterday',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roster.shift', to_field='id'),
        ),
        migrations.AddField(
            model_name='roster',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account', to_field='id'),
        ),
        migrations.AddField(
            model_name='batch',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='roster.roster', to_field='id'),
        ),
    ]
