# Generated by Django 4.1 on 2022-09-20 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterday',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roster.batch'),
        ),
        migrations.AddField(
            model_name='rosterday',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roster.shift'),
        ),
        migrations.DeleteModel(
            name='RosterSheet',
        ),
    ]
