# Generated by Django 4.1 on 2023-01-20 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_module_roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_module_roster.roster', to_field='id'),
        ),
        migrations.AlterField(
            model_name='rosterday',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_module_roster.batch', to_field='id'),
        ),
        migrations.AlterField(
            model_name='rosterday',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_module_roster.roster', to_field='id'),
        ),
        migrations.AlterField(
            model_name='rosterday',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_module_roster.shift', to_field='id'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_module_roster.roster', to_field='id'),
        ),
        migrations.AlterField(
            model_name='staffpersonnel',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_module_roster.batch', to_field='id'),
        ),
        migrations.AlterField(
            model_name='staffpersonnel',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_module_roster.roster', to_field='id'),
        ),
    ]
