# Generated by Django 4.1 on 2022-09-21 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_rosterday_batch_rosterday_shift_delete_rostersheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterday',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roster.batch', to_field='id'),
        ),
        migrations.AlterField(
            model_name='rosterday',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='roster.shift', to_field='id'),
        ),
    ]
