# Generated by Django 4.1 on 2023-03-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_module_budget', '0002_budgetcodeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
