# Generated by Django 4.1 on 2023-03-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_module_calendar', '0003_calendarcodeconfig_schedulecodeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='calendar_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
