# Generated by Django 4.1 on 2022-12-17 06:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalSheet',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('knowledge', models.CharField(blank=True, max_length=4, null=True)),
                ('quality', models.CharField(blank=True, max_length=4, null=True)),
                ('productivity', models.CharField(blank=True, max_length=4, null=True)),
                ('dependability', models.CharField(blank=True, max_length=4, null=True)),
                ('attendance', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'enterprise_module_appraisal_sheet',
            },
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('appraisal_code', models.CharField(blank=True, max_length=64, null=True)),
                ('appraisal_name', models.CharField(blank=True, max_length=256, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('suoervisor', models.CharField(blank=True, max_length=128, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise_account.account', to_field='id')),
            ],
            options={
                'db_table': 'enterprise_module_appraisal',
            },
        ),
    ]
