# Generated by Django 4.1 on 2022-12-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_module_employees', '0001_initial'),
        ('enterprise_module_appraisal', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise_module_employees.employee', to_field='id'),
        ),
    ]
