# Generated by Django 4.1 on 2023-03-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_module_admissions', '0002_initial'),
        ('hospital_module_diagnosis', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='patient',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital_module_admissions.admission', to_field='id'),
        ),
    ]
