# Generated by Django 4.1 on 2022-09-20 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account_name', models.CharField(max_length=126, null=True)),
                ('account_number', models.CharField(max_length=32, null=True)),
                ('bank_name', models.CharField(max_length=126, null=True)),
                ('account_type', models.CharField(max_length=32, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='id')),
            ],
            options={
                'db_table': 'personal_module_account',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('transaction_type', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal_module_accounts.account', to_field='id')),
            ],
            options={
                'db_table': 'personal_module_account_transaction',
            },
        ),
    ]
