# Generated by Django 4.1 on 2022-09-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_module_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank_name',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
    ]
