# Generated by Django 4.1 on 2023-03-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_module_accounts', '0003_accountcodeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
