# Generated by Django 4.1 on 2022-09-26 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
