# Generated by Django 4.1 on 2023-03-06 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_module_services', '0001_initial'),
        ('hotel_module_checkin', '0001_initial'),
        ('hotel_module_bills', '0002_bill_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkincharge',
            name='checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_module_checkin.checkin', to_field='id'),
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_module_services.service', to_field='id'),
        ),
    ]
