# Generated by Django 4.1 on 2022-11-28 07:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('plan_code', models.CharField(blank=True, max_length=32, null=True)),
                ('plan_title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('plan_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='association_account.account', to_field='id')),
            ],
            options={
                'db_table': 'association_module_action_plan',
            },
        ),
        migrations.CreateModel(
            name='PlanStep',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('step_number', models.CharField(blank=True, max_length=16, null=True)),
                ('step_description', models.TextField(blank=True, null=True)),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='association_module_action_plan.actionplan', to_field='id')),
            ],
            options={
                'db_table': 'association_module_action_plan_step',
            },
        ),
    ]
