# Generated by Django 4.1 on 2022-12-17 06:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('folder_number', models.CharField(blank=True, max_length=64, null=True)),
                ('folder_name', models.CharField(blank=True, max_length=256, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise_account.account', to_field='id')),
            ],
            options={
                'db_table': 'enterprise_module_files_folder',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file_number', models.CharField(blank=True, max_length=64, null=True)),
                ('file_name', models.CharField(blank=True, max_length=256, null=True)),
                ('file_type', models.CharField(blank=True, max_length=128, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise_module_files.folder', to_field='id')),
            ],
            options={
                'db_table': 'enterprise_module_file',
            },
        ),
    ]
