# Generated by Django 4.1 on 2022-12-17 06:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('visit_code', models.CharField(blank=True, max_length=64, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('visitor_name', models.CharField(blank=True, max_length=256, null=True)),
                ('visitor_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('arrival', models.TimeField(blank=True, null=True)),
                ('departure', models.TimeField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=128, null=True)),
                ('tag_umber', models.CharField(blank=True, max_length=32, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise_account.account', to_field='id')),
            ],
            options={
                'db_table': 'enterprise_module_reception_visitor',
            },
        ),
    ]
