# Generated by Django 4.1 on 2022-12-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_module_reception', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='tag_umber',
            new_name='tag_number',
        ),
    ]
