# Generated by Django 4.1 on 2022-10-21 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_module_terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeterm',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_terms.term', to_field='id'),
        ),
    ]
