# Generated by Django 4.1 on 2023-03-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module_payables', '0002_payable_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payable',
            name='customer_name',
        ),
    ]
