# Generated by Django 4.1 on 2023-03-06 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_module_guests', '0001_initial'),
        ('hotel_module_rooms', '0001_initial'),
        ('hotel_module_bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedroom',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_module_rooms.room', to_field='id'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_module_guests.guest', to_field='id'),
        ),
    ]
