# Generated by Django 4.1 on 2022-10-14 06:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant_module_tables', '0001_initial'),
        ('restaurant_module_customers', '0001_initial'),
        ('restaurant_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=256)),
                ('reservation_code', models.CharField(blank=True, max_length=64)),
                ('reservation_date', models.DateTimeField(blank=True, null=True)),
                ('number_guests', models.IntegerField(blank=True, null=True)),
                ('number_tables', models.IntegerField(blank=True, null=True)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('reservation_status', models.CharField(blank=True, max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_account.account', to_field='id')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_module_customers.customer', to_field='id')),
            ],
            options={
                'db_table': 'restaurant_module_reservation',
            },
        ),
        migrations.CreateModel(
            name='ReservationCodeConfig',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry_mode', models.CharField(blank=True, max_length=32, null=True)),
                ('prefix', models.CharField(blank=True, max_length=32, null=True)),
                ('suffix', models.CharField(blank=True, max_length=32, null=True)),
                ('last_code', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'restaurant_module_reservation_code_config',
            },
        ),
        migrations.CreateModel(
            name='ReservationTable',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_module_reservations.reservation', to_field='id')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_module_tables.table', to_field='id')),
            ],
            options={
                'db_table': 'restaurant_module_reservation_table',
            },
        ),
    ]
