# Generated by Django 4.1 on 2022-10-05 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant_module_customers', '0001_initial'),
        ('restaurant_module_reservations', '0001_initial'),
        ('restaurant_account', '0002_initial'),
        ('restaurant_module_tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationtable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_module_tables.table', to_field='id'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_account.account', to_field='id'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_module_customers.customer', to_field='id'),
        ),
    ]
