# Generated by Django 4.1 on 2022-09-20 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_status', models.CharField(max_length=64, null=True)),
                ('date_confirmed', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account', to_field='id')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restauarant_invitee', to=settings.AUTH_USER_MODEL, to_field='id')),
            ],
            options={
                'db_table': 'restaurant_module_admin_invitation',
            },
        ),
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_creator', models.BooleanField(default=False)),
                ('access_level', models.CharField(max_length=32, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account', to_field='id')),
                ('personal_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='id')),
            ],
            options={
                'db_table': 'restaurant_module_admin_account_user',
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('admin_access', models.BooleanField(default=False)),
                ('portal_access', models.BooleanField(default=False)),
                ('settings_access', models.BooleanField(default=False)),
                ('menu_access', models.BooleanField(default=False)),
                ('staff_access', models.BooleanField(default=False)),
                ('tables_access', models.BooleanField(default=False)),
                ('customers_access', models.BooleanField(default=False)),
                ('deliveries_access', models.BooleanField(default=False)),
                ('payments_access', models.BooleanField(default=False)),
                ('roster_access', models.BooleanField(default=False)),
                ('reservations_access', models.BooleanField(default=False)),
                ('orders_access', models.BooleanField(default=False)),
                ('kitchen_stock_access', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.account', to_field='id')),
            ],
            options={
                'db_table': 'restaurant_module_admin_access',
            },
        ),
    ]
