# Generated by Django 4.1 on 2022-09-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_module_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='invitee',
            new_name='user',
        ),
        migrations.AddField(
            model_name='invitation',
            name='account_type',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
