# Generated by Django 4.1 on 2022-09-28 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant_account', '0002_initial'),
        ('restaurant_module_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restauarant_invitee', to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_account.account', to_field='id'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='personal_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
        migrations.AddField(
            model_name='access',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_account.account', to_field='id'),
        ),
    ]
