# Generated by Django 4.1 on 2022-09-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_module_admin', '0002_rename_invitee_invitation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='date_confirmed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
