# Generated by Django 4.1 on 2023-01-20 06:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset_number', models.CharField(blank=True, max_length=64, null=True)),
                ('asset_name', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_purchased', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=128, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_account.account', to_field='id')),
            ],
            options={
                'db_table': 'hotel_module_asset',
            },
        ),
    ]
