# Generated by Django 4.1 on 2023-03-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_module_assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='type',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
