# Generated by Django 4.1 on 2023-03-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_module_notes', '0003_notecodeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
