# Generated by Django 4.1 on 2022-11-03 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_module_terms', '0001_initial'),
        ('school_module_students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_terms.term', to_field='id'),
        ),
    ]
