# Generated by Django 4.1 on 2023-03-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association_module_accounts', '0002_accountcodeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
