# Generated by Django 4.1 on 2022-09-28 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('task_group', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'personal_module_task_group',
            },
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('task_item', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(max_length=32, null=True)),
                ('status', models.CharField(max_length=32, null=True)),
                ('task_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal_module_tasks.taskgroup', to_field='id')),
            ],
            options={
                'db_table': 'personal_module_task_item',
            },
        ),
    ]
