# Generated by Django 4.1 on 2022-09-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taskgroup',
            table='personal_module_task_group',
        ),
        migrations.AlterModelTable(
            name='taskitem',
            table='personal_module_task_item',
        ),
    ]
