# Generated by Django 4.1 on 2022-09-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroup',
            name='task_group',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
