# Generated by Django 4.1 on 2022-09-25 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_alter_taskgroup_task_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='task_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.taskgroup', to_field='id'),
        ),
    ]
