# Generated by Django 4.1 on 2023-03-06 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_module_bookings', '0002_bookedroom_room_booking_guest'),
        ('hotel_module_rooms', '0001_initial'),
        ('hotel_module_checkin', '0002_checkin_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='booking_code',
        ),
        migrations.AddField(
            model_name='checkin',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_module_bookings.booking', to_field='id'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_module_rooms.room', to_field='id'),
        ),
    ]
