# Generated by Django 4.1 on 2022-10-19 10:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_account', '0001_initial'),
        ('school_module_classes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('timetable_code', models.CharField(blank=True, max_length=32, null=True)),
                ('timetable_name', models.CharField(blank=True, max_length=256, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_account.account', to_field='id')),
            ],
            options={
                'db_table': 'school_module_timetable',
            },
        ),
        migrations.CreateModel(
            name='TimetableCodeConfig',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry_mode', models.CharField(blank=True, max_length=32, null=True)),
                ('prefix', models.CharField(blank=True, max_length=32, null=True)),
                ('suffix', models.CharField(blank=True, max_length=32, null=True)),
                ('last_code', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'school_module_timetable_code_config',
            },
        ),
        migrations.CreateModel(
            name='TimetableSheet',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_timetable.timetable', to_field='id')),
            ],
            options={
                'db_table': 'school_module_timetable_sheet',
            },
        ),
        migrations.CreateModel(
            name='TimetablePeriod',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=256, null=True)),
                ('period_start', models.TimeField(blank=True, null=True)),
                ('period_end', models.TimeField(blank=True, null=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_timetable.timetable', to_field='id')),
            ],
            options={
                'db_table': 'school_module_timetable_period',
            },
        ),
        migrations.CreateModel(
            name='TimetableClass',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_classes.clase', to_field='id')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_timetable.timetable', to_field='id')),
            ],
            options={
                'db_table': 'school_module_timetable_class',
            },
        ),
    ]
