# Generated by Django 4.1 on 2022-12-17 06:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ledger_code', models.CharField(blank=True, max_length=64, null=True)),
                ('ledger_name', models.CharField(blank=True, max_length=128, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise_account.account', to_field='id')),
            ],
            options={
                'db_table': 'enterprise_module_ledger',
            },
        ),
        migrations.CreateModel(
            name='LedgerItem',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_date', models.DateTimeField(null=True)),
                ('reference_number', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('item_type', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise_module_ledger.ledger', to_field='id')),
            ],
            options={
                'db_table': 'enterprise_module_ledger_item',
            },
        ),
    ]
