# Generated by Django 4.1 on 2022-10-14 06:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant_account', '0001_initial'),
        ('restaurant_module_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_code', models.CharField(blank=True, max_length=64, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=256, null=True)),
                ('delivery_status', models.CharField(blank=True, max_length=64, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_account.account', to_field='id')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_module_orders.order', to_field='id')),
            ],
            options={
                'db_table': 'restaurant_module_delivery',
            },
        ),
    ]
