# Generated by Django 4.1 on 2022-10-19 10:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_module_assessment', '0001_initial'),
        ('school_account', '0001_initial'),
        ('school_module_classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report_code', models.CharField(blank=True, max_length=32, null=True)),
                ('report_name', models.CharField(blank=True, max_length=256, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_account.account', to_field='id')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_classes.clase', to_field='id')),
            ],
            options={
                'db_table': 'school_module_report',
            },
        ),
        migrations.CreateModel(
            name='ReportCodeConfig',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry_mode', models.CharField(blank=True, max_length=32, null=True)),
                ('prefix', models.CharField(blank=True, max_length=32, null=True)),
                ('suffix', models.CharField(blank=True, max_length=32, null=True)),
                ('last_code', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'school_module_report_code_config',
            },
        ),
        migrations.CreateModel(
            name='ReportSheet',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_reports.report', to_field='id')),
            ],
            options={
                'db_table': 'school_module_report_sheet',
            },
        ),
        migrations.CreateModel(
            name='ReportAssessment',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_assessment.assessment', to_field='id')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_reports.report', to_field='id')),
            ],
            options={
                'db_table': 'school_module_report_assessment',
            },
        ),
    ]
