# Generated by Django 4.1 on 2022-09-25 20:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('budget_name', models.CharField(blank=True, max_length=128, null=True)),
                ('budget_type', models.CharField(max_length=32, null=True)),
            ],
            options={
                'db_table': 'personal_module_budget',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_number', models.CharField(blank=True, max_length=16, null=True)),
                ('item_description', models.CharField(blank=True, max_length=256, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.budget', to_field='id')),
            ],
            options={
                'db_table': 'personal_module_budget_income',
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_number', models.CharField(blank=True, max_length=16, null=True)),
                ('item_description', models.CharField(blank=True, max_length=256, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.budget', to_field='id')),
            ],
            options={
                'db_table': 'personal_module_budget_expendture',
            },
        ),
    ]
