# Generated by Django 4.1 on 2022-09-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_budget_budget_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='item_description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='item_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='item_description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='item_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
