# Generated by Django 4.1 on 2023-03-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_module_budget', '0003_budgetcodeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='budget_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
