# Generated by Django 4.1 on 2023-03-04 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module_products', '0002_product_product_image'),
        ('shop_module_suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplierItem',
            new_name='SupplierProduct',
        ),
        migrations.AlterModelTable(
            name='supplierproduct',
            table='shop_module_supplier_product',
        ),
    ]
