# Generated by Django 4.1 on 2022-10-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_module_lesson_plan', '0002_initial'),
        ('school_module_teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_teachers.teacher', to_field='id'),
        ),
    ]
