# Generated by Django 4.1 on 2022-10-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_module_teachers', '0001_initial'),
        ('school_module_subjects', '0003_alter_subject_department'),
        ('school_module_lesson_plan', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_subjects.subject', to_field='id'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_teachers.teacher', to_field='id'),
        ),
    ]
