# Generated by Django 4.1 on 2022-11-01 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_module_terms', '0002_alter_activeterm_term'),
        ('school_module_lesson_plan', '0004_alter_lessonplan_subject_alter_lessonplan_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_terms.term', to_field='id'),
        ),
    ]
