# Generated by Django 4.1 on 2023-01-20 06:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_module_rooms', '0001_initial'),
        ('hotel_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingCodeConfig',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry_mode', models.CharField(blank=True, max_length=32, null=True)),
                ('prefix', models.CharField(blank=True, max_length=32, null=True)),
                ('suffix', models.CharField(blank=True, max_length=32, null=True)),
                ('last_code', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'hotel_module_housekeeping_code_config',
            },
        ),
        migrations.CreateModel(
            name='Housekeeping',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('housekeeping_code', models.CharField(blank=True, max_length=64)),
                ('housekeeping_date', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_account.account', to_field='id')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_module_rooms.room', to_field='id')),
            ],
            options={
                'db_table': 'hotel_module_housekeeping',
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_number', models.IntegerField(blank=True, null=True)),
                ('item_description', models.CharField(blank=True, max_length=256, null=True)),
                ('item_status', models.CharField(blank=True, max_length=64, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('housekeeping', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_module_housekeeping.housekeeping', to_field='id')),
            ],
            options={
                'db_table': 'hotel_module_housekeeping_checklist',
            },
        ),
    ]
