# Generated by Django 4.1 on 2023-03-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_module_housekeeping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='item_description',
            new_name='task_description',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='item_status',
            new_name='task_status',
        ),
    ]
