# Generated by Django 4.1 on 2023-03-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_module_housekeeping', '0002_rename_item_description_checklist_task_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='task_description',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='task_status',
            new_name='item_status',
        ),
    ]
