# Generated by Django 4.1 on 2022-10-05 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant_module_tables', '0001_initial'),
        ('restaurant_module_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant_module_tables.table', to_field='id'),
        ),
    ]
