# Generated by Django 4.1 on 2022-10-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_module_orders', '0002_ordercodeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
