# Generated by Django 4.1 on 2023-03-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_module_purchasing', '0001_initial'),
        ('shop_module_suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasing',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop_module_suppliers.supplier', to_field='id'),
        ),
    ]
