# Generated by Django 4.1 on 2023-03-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module_purchasing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasing',
            name='purchasing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
