# Generated by Django 4.1 on 2023-03-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module_invoice', '0003_invoice_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_code',
            new_name='invoice_number',
        ),
    ]
