# Generated by Django 4.1 on 2023-03-05 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module_invoice', '0005_remove_invoice_customer_name_alter_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_contact',
        ),
    ]
