# Generated by Django 4.1 on 2022-09-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountuser',
            old_name='account_user',
            new_name='personal_user',
        ),
    ]
