# Generated by Django 4.1 on 2022-11-03 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_module_subjects', '0001_initial'),
        ('school_module_assessment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_subjects.subject', to_field='id'),
        ),
    ]
