# Generated by Django 4.1 on 2022-10-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_module_assessment', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssessmentClass',
        ),
    ]
