# Generated by Django 4.1 on 2022-10-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_module_classes', '0002_initial'),
        ('school_module_subjects', '0002_initial'),
        ('school_module_assessment', '0004_delete_assessmentclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_classes.clase', to_field='id'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_subjects.subject', to_field='id'),
        ),
    ]
