# Generated by Django 4.1 on 2022-10-26 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_module_terms', '0002_alter_activeterm_term'),
        ('school_module_assessment', '0004_alter_assessment_clase_alter_assessment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_terms.term', to_field='id'),
        ),
    ]
