# Generated by Django 4.1 on 2022-10-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_module_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='customer_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
