# Generated by Django 4.1 on 2023-02-13 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_module_drugs', '0001_initial'),
        ('hospital_account', '0001_initial'),
        ('hospital_module_dispensary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenseitem',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospital_module_drugs.drug', to_field='id'),
        ),
        migrations.AddField(
            model_name='dispense',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospital_account.account', to_field='id'),
        ),
    ]
