# Generated by Django 4.1 on 2023-03-07 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_module_admissions', '0002_initial'),
        ('hospital_module_prescriptions', '0001_initial'),
        ('hospital_module_dispensary', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispense',
            name='dispense_status',
        ),
        migrations.RemoveField(
            model_name='dispense',
            name='patient',
        ),
        migrations.AddField(
            model_name='dispense',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital_module_admissions.admission', to_field='id'),
        ),
        migrations.AddField(
            model_name='dispense',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospital_module_prescriptions.prescription', to_field='id'),
        ),
    ]
