# Generated by Django 4.1 on 2023-03-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_module_dispensary', '0004_remove_dispense_dispense_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenseitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
