# Generated by Django 4.1 on 2022-10-22 07:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school_module_classes', '0004_alter_department_department_head_departmentclass'),
        ('school_module_fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesTarget',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_classes.clase', to_field='id')),
                ('fees', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_module_fees.fees', to_field='id')),
            ],
            options={
                'db_table': 'school_module_fees_target',
            },
        ),
    ]
