# Generated by Django 4.1 on 2023-02-13 20:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugCodeConfig',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry_mode', models.CharField(blank=True, max_length=32, null=True)),
                ('prefix', models.CharField(blank=True, max_length=32, null=True)),
                ('suffix', models.CharField(blank=True, max_length=32, null=True)),
                ('last_code', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'hospital_module_drug_code_config',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ndc_number', models.CharField(blank=True, max_length=64, null=True)),
                ('drug_name', models.DateTimeField(blank=True, null=True)),
                ('generic_name', models.CharField(blank=True, max_length=256, null=True)),
                ('drug_type', models.CharField(blank=True, max_length=256, null=True)),
                ('unit_dose', models.CharField(blank=True, max_length=32, null=True)),
                ('drug_category', models.CharField(blank=True, max_length=256, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=64, null=True)),
                ('purchased_date', models.DateField(blank=True, null=True)),
                ('initial_quantity', models.IntegerField(blank=True, null=True)),
                ('dispensed_quantity', models.IntegerField(blank=True, null=True)),
                ('remaining_quantity', models.IntegerField(blank=True, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=128, null=True)),
                ('storage_bin', models.CharField(blank=True, max_length=128, null=True)),
                ('refill_ordered', models.IntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospital_account.account', to_field='id')),
            ],
            options={
                'db_table': 'hospital_module_drug',
            },
        ),
    ]
