# Generated by Django 4.1 on 2022-09-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menugroup',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='menugroup',
            name='menu_group',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
