# Generated by Django 4.1 on 2023-03-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_module_menu', '0002_menugroupcodeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='menugroup',
            name='menu_group_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
