# Generated by Django 4.1 on 2022-12-17 06:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=128, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=128, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=128, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=128, null=True)),
                ('acknowledged_date', models.DateField(blank=True, null=True)),
                ('completed_by', models.CharField(blank=True, max_length=128, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enterprise_module_procurement_order_review',
            },
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('procurement_code', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.CharField(blank=True, max_length=256, null=True)),
                ('order_code', models.CharField(blank=True, max_length=64, null=True)),
                ('order_type', models.CharField(blank=True, max_length=128, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=256, null=True)),
                ('vendor_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('vendor_email', models.CharField(blank=True, max_length=128, null=True)),
                ('vendor_address', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise_account.account', to_field='id')),
            ],
            options={
                'db_table': 'enterprise_module_procurement',
            },
        ),
    ]
